### ISSUE TITLE
Please opensource the script which was used to collect these quotes

### ISSUE THREAD

**Issue by donenoyes** [coderdudex/Less-Real-Data#1]
It would be helpful if you could opensource the script that was used to scrape these quotes and if possible the instruction of its usage

**Comment by Decode84** [comment]
I made a python script to do it, and you can find it here. 
https://github.com/KB885/Less-Real-Data/blob/main/web.py

Get python3 and run the script through that. 

Install these packages.
- BeautifulSoup
- Pandas
- Numpy
- Tqdm

**Comment by donenoyes** [comment]
Thank you so much! Very helpful!
